apiVersion: v1
data:
  app-config.yml: |
    message : "Hello, %s from a ConfigMap !"
    level : INFO
kind: ConfigMap
metadata:
  name: app-config
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: mock
spec:
  replicas: 1
  selector:
    app: mock
  template:
    metadata:
      labels:
        app: mock
    spec:
      containers:
      - name: mock-container
        image: k8s.gcr.io/pause:2.0
        ports:
        - containerPort: 9949
          protocol: TCP
